### ISSUE TITLE
empty_tag_value not obeying xsi:nil ?

### ISSUE THREAD

**Issue by l8nite** [savonrb/nori#79] opened 2017-09-15 06:30 UTC
I'd like to get `nil` when `xsi:nil="true"`, and a blank string when the tag is empty.

```
irb(main):025:0> parser = Nori.new(empty_tag_value: "")
=> #<Nori:0x00001c2965f690 @options={:strip_namespaces=>false, :delete_namespace_attributes=>false, :convert_tags_to=>nil, :convert_attributes_to=>nil, :empty_tag_value=>"", :advanced_typecasting=>true, :convert_dashes_to_underscores=>true, :parser=>:nokogiri}>
irb(main):026:0> parser.parse('<foo/>')
=> {"foo"=>""}
irb(main):027:0> parser.parse('<foo xsi:nil="true"/>')
=> {"foo"=>""}
irb(main):028:0>
```

**Comment by pcai** [comment] 2024-09-05 21:32
Looks like dupe of #63

**Closed by pcai** 2024-09-05 21:32 UTC

**Comment by sguth-affirm** [comment] 2024-09-05 21:34
7 years old backlog cleanup?!  Nice!
